apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: durable-locks
resources:
  - ../../base/celld
  - ../../base/seaweedfs
  - namespace.yaml
secretGenerator:
  - name: s3-credentials
    literals:
      - AWS_ACCESS_KEY_ID=durable-locks
      - AWS_SECRET_ACCESS_KEY=durable-locks-secret
    options:
      labels:
        app.kubernetes.io/name: seaweedfs
        app.kubernetes.io/component: object-storage
        app.kubernetes.io/part-of: durable-locks
patches:
  - path: celld-endpoints.yaml
  - target:
      kind: Deployment
      name: seaweedfs
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          kubernetes.io/hostname: kind-worker
  - target:
      kind: PersistentVolumeClaim
      name: seaweedfs-data
    patch: |-
      - op: add
        path: /spec/storageClassName
        value: standard
