apiVersion: v1
kind: Service
metadata:
  name: s3-seaweedfs
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: object-storage
    app.kubernetes.io/part-of: durable-locks
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: seaweedfs
  ports:
    - name: s3
      port: 9000
      targetPort: s3
      protocol: TCP
    - name: console
      port: 80
      targetPort: console
      protocol: TCP
